name: o_woman
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.2+2

environment:
  sdk: '>=3.2.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  dio: ^5.4.0
  logger: ^2.0.2+1
  internet_connection_checker: ^1.0.0+1
  hive: ^2.2.3
  intl: ^0.18.1
  path_provider: ^2.1.0
  fluttertoast: ^8.2.3
  flutter_screenutil: ^5.9.0
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  social_share: ^2.2.1
  cached_network_image: ^3.2.3
  camera: ^0.10.5+6
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  dartz: ^0.10.1
  dropdown_button2 : ^2.3.9
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  encrypt: ^5.0.3
  pin_code_fields: ^8.0.0
  scrollable_positioned_list: ^0.3.8
  dotted_border: ^2.0.0+3
  google_maps_flutter: ^2.5.0
  device_preview: ^1.0.0
  syncfusion_flutter_charts: ^24.1.45
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  flutter_windowmanager: ^0.2.0
  workmanager: ^0.5.2
  flutter_inappwebview: ^5.8.0
  contacts_service: ^0.6.3
  permission_handler: ^11.1.0
  speech_to_text: ^6.5.1
  flutter_tts: ^3.8.5
  another_flushbar: ^1.12.30
  image_cropper: ^5.0.1
  carousel_slider: ^4.2.1
  local_auth: ^2.1.8
  alarm: ^3.0.6
  modal_progress_hud_nsn: ^0.5.0
  intl_phone_field: ^3.2.0
  jwt_decoder: ^2.0.1





dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/music/
     - assets/loading_json/
     - assets/images/intro_slider/
     - assets/images/auth/
     - assets/images/dashboard/
     - assets/images/svg/
     - assets/images/intro_qus/
     - assets/images/intro_qus/cycle_tracking/
     - assets/images/intro_qus/fertility/
     - assets/images/icons/
     - assets/images/intro_qus/menstrual/
     - assets/images/intro_qus/nutrition_health/
     - assets/images/intro_qus/general_health/

     - assets/images/icons/symptoms_moods/
     - assets/images/icons/add_pill/
     - assets/json_files/
     - assets/images/icons/community/
     - assets/images/analytics/
     - assets/images/icons/home_health/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Bold.ttf
         - asset: assets/fonts/Poppins-Light.ttf
         - asset: assets/fonts/Poppins-Medium.ttf
         - asset: assets/fonts/Poppins-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
